version: '3'
services:
  nginx:
    container_name: apollo-front-nginx
    image: marvinvov/apollo-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - apollo_service-shared-net
networks:
  apollo_service-shared-net: # Use a pre-existing network
    external: true